VisualComposer/builder

public/editor/services/api/lib/dividerShape.js, public/sources/attributes/boxShadow/Component.js, public/sources/attributes/designOptionsAdvanced/Component.js, public/sources/attributes/divider/Component.js
Updated range attribute input value on change.
- Updated gradient overlay range input
- Updated box-shadow range input
- Updated dividers range input
=> Range input values

public/editor/services/cook/service.js
Add source ID for getdata dynamic content VC-453
=> Add source ID for getdata dynamic content VC-453

elements/singleImage/singleImage/component.js, elements/singleImage/singleImage/styles.css, public/editor/services/cook/service.js
- Fix: Image display works properly 
- Fix: Post data fetch for dynamic content works properly
=> 18.2 hotfix

CONTRIBUTING.md, plugin-wordpress.php, tests/phpunit/Framework/test-requirements.php
Update only when all changes are confirmed
=> Update contribute file

visualcomposer/Modules/Editors/EditPostLinks/Controller.php, visualcomposer/Modules/Editors/Frontend/MenuController.php, visualcomposer/Modules/Editors/FrontendLayoutSwitcher/BundleController.php, visualcomposer/Modules/Vendors/GutenbergAttributeController.php, visualcomposer/Modules/Vendors/WpmlController.php
Creating new translation from VC page always opens classic mode with tinymce disabled
Fixed menu nav URLS with lang code
VC-582
=> VC-582 WMPL improvements

tests/cypress/fixtures/rowColumn.json, tests/cypress/integration/rowColumn.spec.js
- Add fixture for rowColumn.spec.js test
- Add command for Design Options Advanced
- Add more Row element attributes checks
=> Enhance rowColumn e2e test

elements/shortcode/shortcode/component.js, elements/wpWidgetsCustom/wpWidgetsCustom/component.js, elements/wpWidgetsDefault/wpWidgetsDefault/component.js, visualcomposer/Modules/Assets/EnqueueController.php, visualcomposer/Modules/Assets/VcwbWpScripts.php, visualcomposer/Modules/Elements/Traits/ShortcodesTrait.php, visualcomposer/Modules/Elements/WpWidgets/WpWidgetsController.php
Update widgets, shortcodes rendering process, create custom WP_SCRIPT handler VC-633
=> Update widgets, shortcodes rendering process, create custom WP_SCRIPT VC-633

readme.txt
=> VC-671 add contributor

visualcomposer/Modules/System/Cache/CacheController.php
The rest of the cache is cleared automatically on editor save
=> VC-701 clear cache on single post save

visualcomposer/Modules/Assets/EnqueueController.php
=> Fix VC-719 object properties import for global wp_scripts override

elements/row/row/component.js, public/editor/stores/assets/assetsStorage.js, public/editor/stores/assets/lib/attributeLibNames.json, public/sources/attributes/attribute.js, public/sources/attributes/parallax/Component.js, public/sources/attributes/parallax/GetAttributeLibs.js
- Added logic for extra options like parallax
=> Extra options for addon VC-662

public/components/account/activatePremiumScreen.js, tests/phpunit/helpers/test-helpers-url.php, visualcomposer/Helpers/Localizations.php, visualcomposer/Helpers/Utm.php
Signed-off-by: Pavel I <pavel@visualcomposer.com>
=> VC-900 VC-901 VC-902 update free activation texts and UTM

.circleci/config.yml
The configuration is fixed but needs to fix tests itself before merge
=> Phpunit tests does not work VC-1047

tests/cypress/fixtures/basicButton.json, tests/cypress/fixtures/customWidget.json, tests/cypress/fixtures/defaultWidget.json, tests/cypress/fixtures/googleFontsHeading.json, tests/cypress/fixtures/outlineButton.json, tests/cypress/fixtures/separator.json, tests/cypress/fixtures/shortcode.json, tests/cypress/fixtures/singleImage.json, tests/cypress/fixtures/youtubePlayer.json, tests/cypress/integration/basicButton.spec.js, tests/cypress/integration/customWidget.spec.js, tests/cypress/integration/defaultWidget.spec.js, tests/cypress/integration/googleFontsHeading.js, tests/cypress/integration/outlineButton.spec.js, tests/cypress/integration/separator.spec.js, tests/cypress/integration/settingsPanel.spec.js, tests/cypress/integration/shortcode.spec.js, tests/cypress/integration/singleImage.spec.js, tests/cypress/integration/vimeoPlayer.spec.js, tests/cypress/integration/youtubePlayer.spec.js
Used inner commands to set elements attributes in Edit Form.
=> Refactor e2e tests

public/editor/stores/workspaceStorage.js, visualcomposer/Helpers/Localizations.php
Add ID copy notification VC-1055
=> Add ID copy notification VC-1055

visualcomposer/Modules/License/Pages/GettingStarted.php
=> Remove about page Vc 1160

tests/phpunit/modules/Settings/test-mainpage.php, visualcomposer/Modules/License/Pages/GettingStarted.php, visualcomposer/Modules/Settings/Pages/About.php, visualcomposer/Modules/Settings/Pages/Settings.php
=> Adjust render issue VC-1160

visualcomposer/Modules/License/Pages/GoPremium.php
Add notice about activation VC-1064
=> Add notice about activation VC-1064

visualcomposer/Modules/License/Pages/GoPremium.php
Add getting started page to notices VC-1064
=> Add getting started page to notices VC-1064

visualcomposer/Helpers/Assets.php, visualcomposer/Modules/Assets/EnqueueController.php
=> Adjust style jumping VC-1168

public/sources/attributes/gutenbergEditor/lib/iframeControlStyles.js, visualcomposer/Modules/Vendors/Gutenberg/AttributeController.php
Adjust gutenberg editor element ui issues VC-1195
=> Adjust gutenberg editor element ui issues VC-1195

tests/assets/php-e2e-locale.js, tests/cypress/integration/scriptLocalizationsSequence.spec.js, tests/php-e2e-actions/actions/clean-e2e-posts-db.php, tests/php-e2e-actions/actions/test-asset-enqueue.php, tests/php-e2e-actions/helpers.php, tests/php-e2e-actions/init.php, tests/php-e2e-actions/shortcodes.php
Create localization bug test VC-1201
=> Introduce php-e2e actions for cypress e2e tests

public/components/wpVcSettings/dashboard.js, visualcomposer/Modules/Settings/Pages/SystemStatus.php
=> Fix title change in Dashboard

public/components/account/videoScreen.js, public/components/navbar/controls/wordpressAdminControl.js, public/sources/less/wpsettings-update/styles.less
- Update Take Tutorial button loading style
- Reset page layout on Tutorial Template Reset
=> Update tutorial template VC-1423

public/components/dnd/dndDataSet.js, public/components/dnd/helper.js, public/components/layoutHelpers/contentEditable/contentEditableComponent.js
Double click opens editForm, inline editor opens on double click VC-1516
=> Double click opens editForm, inline editor opens on double click VC-1516

public/components/layoutHelpers/contentControls/component.js
Fixed an issue when dragging the last column of a row into a different row broke the editor VC-1624
=> VC-1624 DnD Column causes error

visualcomposer/Modules/Assets/EnqueueController.php, visualcomposer/Modules/Hub/Pages/PremiumTeasers.php, visualcomposer/Modules/Vendors/WooCommerceSquareController.php
VC-1610 Create enqueue filter to skip enqueue, use this filter for WooCommerce Square plugin wp_enqueue_scripts handler to avoid duplication
=> VC-1610 Create vendor for WooCommerce Square plugin

.circleci/config.yml, tests/cypressElectron/cypress/integration/panels/settingsPanel.spec.js, tests/cypressElectron/cypress/integration/panels/templatesPanel.spec.js, tests/cypressElectron/cypress/integration/panels/treeView.spec.js
=> Update e2e tests selectors and config

package.json
=> VC-1922 Resolve exact version of @babel/runtime to fix plugin

public/sources/attributes/attachimage/Component.js
after dynamic content is closed inside attachimage attribute
=> VC-1874 and VC-1875 set empty images state

visualcomposer/Modules/Hub/Pages/PremiumTeasers.php, visualcomposer/Modules/Settings/Traits/SubMenu.php, visualcomposer/resources/views/settings/layouts/dashboard-main-layout.php
…ure to always register tab information
=> VC-2055 fix teasers and submenu conflict on page registration

readme.txt
Changelog for 39.0 added to the readme.txt file
=> Update readme.txt with changelog

readme.txt
Update link to the new location
=> Update readme.txt with Help Center

readme.txt
Changelog for the version 44.0 added
=> Changelog 44.0 - readme.txt

readme.txt
Updated 'Font Manager' link in readme
=> MAR-1448 readme update

readme.txt
Made changes in line 11
Changed 'maintenance sode' to 'maintenance mode'
=> VC-2842 readme.txt typo correction

readme.txt
Updated readme.txt with changelog for 44.2.2
=> Updated readme.txt with changelog for 44.2.2

readme.txt
Reverts VisualComposer/builder#2062
=> Revert "Updated readme.txt with changelog for 44.2.2"

readme.txt
=> Changelog 44.3.1

readme.txt
Readme.txt changelog has been updated with the information about 45.0.1
=> Changelog update 45.0.1

visualcomposer/Helpers/Status.php
Related issues: IS-128
Related PRs: #2163, indystack/wp-restrictions#5
=> IS-129 Add filter for getFileSystemStatus method

elements/shortcode/shortcode/component.js, public/components/layoutHelpers/contentEditable/contentEditableComponent.js, public/editor/modules/layout/module.js, public/editor/services/api/lib/elementComponent.js, public/tools/updateHtmlWithServer.js, visualcomposer/Modules/Elements/AjaxShortcode/Controller.php
VC-3122 merge multi ajax requests with shortcodes in one ajax request
VC-3122 merge multi ajax requests with shortcodes in one ajax request
=> VC-3122 merge multi ajax requests with shortcodes in one ajax request

readme.txt
Readme.txt updated with the latest changes for the release
=> Update changelog for 45.1.2

elements/heroSection/heroSection/component.js, elements/heroSection/heroSection/cssMixins/backgroundColor.pcss, elements/heroSection/heroSection/cssMixins/backgroundPosition.pcss, elements/heroSection/heroSection/index.js, elements/heroSection/heroSection/settings.json
[Feature section PR](https://github.com/VisualComposer/builder/pull/2420) should be merged before merging this one
=> VC-3247 Update Hero Section background

readme.txt
=> Update readme 45.3.0

readme.txt
=> Update readme 45.4.0

readme.txt
=> Update readme 45.4.1

readme.txt
=> Update readme 45.5.0

readme.txt
=> Update readme 45.6.0

readme.txt
=> Update readme 45.7.0

readme.txt
=> Update readme 45.8.0

readme.txt
=> Update readme 45.9.0

readme.txt
=> Update readme 45.11.0

readme.txt
=> Update readme 45.12.0

readme.txt
=> Update readme 45.13.0
